"""
Reporter Subagent — generates human-readable security briefings.

This is the final stage of the pipeline. It reads the analysis results
and produces a polished, actionable daily security briefing in Markdown
(and optionally HTML) format.
"""

from datetime import datetime, timezone

from deepagents import create_deep_agent

from config import LLM_MODEL, REPORTS_DIR, LOCAL_MONITORING_ENABLED, PROTECTED_SERVICES, PROTECTED_PORTS


REPORTER_INSTRUCTIONS = """\
You are a Threat Intelligence Reporter. Your job is to produce a clear,
actionable daily security briefing from the analysis results.

## ⚠️  CRITICAL SAFETY CONSTRAINT
This server has PROTECTED SERVICES that must NEVER be restarted, modified, or
interfered with by remediation commands:
- **nginx on port 80** — serves a valuable production application
- For nginx-related CVEs: REPORT them but mark remediation as "MANUAL REVIEW
  REQUIRED — do NOT restart nginx without coordinating with the app owner."
- Never include `systemctl restart nginx` or `systemctl stop nginx` in commands.
- Other services (sshd, etc.) may include restart commands as normal.

## Report Template

Read the analysis data from /data/analysis_results.json and produce a
Markdown report with the following structure:

---

# 🔒 Daily Threat Intelligence Briefing
**Date:** [today's date]
**System:** [hostname from inventory]
**Generated by:** Threat Intel Analyst Agent

## Executive Summary
[2-3 sentences: How many threats found, how many relevant to this system,
top severity, any active exploits detected]

## 🔴 Critical Actions Required
[List items with priority >= 15, with exact remediation commands]

## 🟠 High Priority Vulnerabilities
[List items with priority 10-14.9]

## 🟡 Medium Priority Items
[List items with priority 5-9.9]

## Vulnerability Details
[For each relevant CVE, a mini-section with:]
- **CVE ID** | CVSS: X.X | EPSS: X.XX | Priority: X.X
- **Affected:** package name & version on this system
- **Description:** 1-2 sentences
- **Remediation:** specific command to run
- **References:** link to NVD, advisory

## IOC Watchlist
[Table of IOCs from ThreatFox that could affect this system]
| IOC Type | Value | Threat | Confidence |

{log_findings_section}

## Security News Highlights
[Top 5 most relevant articles from RSS feeds with links]

## System Inventory Snapshot
[Brief summary: packages, services, ports, Docker containers]

## Appendix: All Data Sources Queried
[List of feeds with timestamps and record counts]

---

## Output Instructions

1. Write the Markdown report to /reports/briefing_YYYYMMDD.md
2. Keep the language professional but accessible — assume the reader is
   a system administrator, not necessarily a security expert.
3. For remediation commands, be SPECIFIC:
   - Use `sudo apt update && sudo apt upgrade <package>` not just "update packages"
   - Include version pins when relevant: `pip install package>=X.Y.Z`
   - Note if a service restart is needed: `sudo systemctl restart <service>`
   - ⚠️  EXCEPTION: NEVER suggest restarting nginx — mark as MANUAL REVIEW
4. If there are NO critical/high items, say so clearly — that's good news!
5. If local log monitoring found issues, give them prominence — those are
   active, real-time findings, not just theoretical vulnerabilities.
6. For nginx-related findings (CVEs or suspicious web requests), include a
   separate "⚠️ Nginx / Port 80 — Manual Review" section so the admin can
   plan maintenance windows for the production app.
"""

LOG_FINDINGS_SECTION = """
## 🔍 Local Activity Findings
[Findings from local log analysis, organized by severity:]
- SSH brute force attempts: X from Y unique IPs
- Suspicious web requests: list of probed paths
- Failed sudo attempts: details
- Any IOC correlations with ThreatFox data

[If source IPs match known threat actors, highlight prominently]
"""

NO_LOG_FINDINGS = """
## Local Activity Monitoring
Local log monitoring is currently disabled. Enable it by setting
`LOCAL_MONITORING_ENABLED=true` in `.env` for active threat detection
on servers with running services.
"""


def create_reporter_agent():
    """Create the Reporter subagent for generating security briefings."""
    log_section = LOG_FINDINGS_SECTION if LOCAL_MONITORING_ENABLED else NO_LOG_FINDINGS
    instructions = REPORTER_INSTRUCTIONS.format(log_findings_section=log_section)

    return create_deep_agent(
        model=LLM_MODEL,
        tools=[],
        system_prompt=instructions

   )
